# Site settings
title: Formr
email: tim@timgavin.name
description: > # this means to ignore newlines until "baseurl:"
  Formr is a PHP micro-framework which installs easily and helps you build and validate forms quickly, painlessly, and without all the complicated, messy overhead.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: timgavin
github_username:  timgavin
google_analytics: UA-2126511-9
markdown: kramdown
permalink: /blog/:title/
