# Site settings
title: Formr
email: tim@timgavin.name
description: > # this means to ignore newlines until "baseurl:"
  Formr is a PHP micro-framework form class which installs easily and helps you build and validate PHP forms quickly, painlessly, and without all the complicated, messy overhead.
baseurl: ""
url: "https://formr.github.io"
github_username:  timgavin
google_analytics: UA-2126511-9
markdown: kramdown
permalink: /blog/:title/
highlighter: rouge
plugins:
  - jekyll-seo-tag